dashboard_authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name='dashboard_auth'

urlpatterns = [
     path('login', login_view, name="login"), 
     path('register', register_user, name="register"),
     path("logout", LogoutView.as_view(), name="logout"),
]

shop_app/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from . import views
from rest_framework_simplejwt import views as jwt_views


app_name = 'shop_app'

#EXCLUDED_URLS_FOR_MAIN_APP = [settings.STATIC_URL.strip('/'),settings.MEDIA_URL.strip('/'),'api']

urlpatterns = [
    path('api/user', views.AuthProfileView.as_view()),
    path('api/products', views.ProductView.as_view()),
    path('api/products/<int:pk>', views.ProductDetailView.as_view()),
    path('api/filters', views.ProductFiltersView.as_view()),
    path('api/purchases', views.PurchaseView.as_view()),
    path('api/purchase/order', views.PurchaseView.as_view()),
    path('api/purchase/order_by_bot', views.PurchaseOrderByBotView.as_view()),
    path('api/download-db', views.download_database),
    path('api/csrf',views.CsrfTokenView.as_view()),
    path('api/token/', 
          jwt_views.TokenObtainPairView.as_view(), 
          name ='token_obtain_pair'),
    path('api/token/refresh/', 
          jwt_views.TokenRefreshView.as_view(), 
          name ='token_refresh'),
    re_path(r'^(?!media|static).*$', views.index, name='main_app'),
    #path('', views.index, name='main_app'),
]

uhf_rfid_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/auth/', include('dashboard_authentication.urls',namespace='dashboard_auth')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('', include('shop_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard_authentication/models.py
from django.db import models

# Create your models here.

dashboard_authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

dashboard_authentication/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

# Create your views here.
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, SignUpForm
#from backend.settings import GITHUB_AUTH
GITHUB_AUTH = False

def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('dashboard:welcome'))
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "accounts/login.html", {"form": form, "msg": msg, "GITHUB_AUTH": GITHUB_AUTH})


def register_user(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = 'User created successfully.'
            success = True

            # return redirect("/login/")

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "accounts/register.html", {"form": form, "msg": msg, "success": success})

dashboard_authentication/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">

                    <h3 class="mb-4">Login</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                            Add your credentials
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <form role="form" method="post" action="">

                        {% csrf_token %}                   

                        <div class="input-group mb-3">
                            {{ form.username }}
                        </div>
                        
                        <div class="input-group mb-4">
                            {{ form.password }}
                        </div>
                        
                        <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4">Login</button>

                    </form>

                    <p class="mb-0 text-muted">Don’t have an account? <a href="{% url 'dashboard_auth:register' %}" >Sign UP</a></p>

                    <br />

                    {% if GITHUB_AUTH %}
                    <div class="mx-2">
                        <form method="post" action="/social_login/github/login/?next=%2F">
                            {% csrf_token %}
                            <button class="btn btn-light" type="submit" style="background-color: #ffffff; border-color: #ffffff;">
                                <i class="feather icon-github auth-icon"></i></button>
                        </form>
                        <span class="mx-1">Sign IN with GitHub</span>
                    </div>                   
                    {% endif %}   

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

dashboard_authentication/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Sign up</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                            Add your credentials
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <!-- Hide the form on success -->
                    {% if success %}

                        <a href="{% url 'dashboard_auth:login' %}" class="btn btn-primary shadow-2 mb-4">Sign IN</a>

                    {% else %}

                        <form role="form" method="post" action="">

                            {% csrf_token %}                    

                            <div class="input-group mb-3">
                                {{ form.username }}
                            </div>
                            <span class="text-error">{{ form.username.errors }}</span>

                            <div class="input-group mb-3">
                                {{ form.email }}
                            </div>
                            <span class="text-error">{{ form.email.errors }}</span>

                            <div class="input-group mb-4">
                                {{ form.password1 }}
                            </div>
                            <span class="text-error">{{ form.password1.errors }}</span>

                            <div class="input-group mb-4">
                                {{ form.password2 }}
                            </div>
                            <span class="text-error">{{ form.password2.errors }}</span>
                            
                            <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4">Register</button>

                        </form>

                        <p class="mb-0 text-muted">Already have an account? <a href="{% url 'dashboard_auth:login' %}" >Login</a></p>
                    
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock content %}