dashboard/tables/actual_purchase/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('actual_pururchase',views.PurchaseListView.as_view(), name='actual_purchase_index'),
    path('actual_pururchase/create', views.actual_purchase_create, name='actual_purchase_create'),
    path('actual_pururchase/update/<int:pk>', views.actual_purchase_edit, name='actual_purchase_edit'),
    path('actual_pururchase/delete/<int:pk>', views.actual_purchase_delete, name='actual_purchase_delete'),
]

dashboard/tables/product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('product',views.ProductListView.as_view(), name='product_index'),
    path('product/create', views.product_create, name='product_create'),
    path('product/update/<int:pk>', views.product_edit, name='product_edit'),
    path('product/delete/<int:pk>', views.product_delete, name='product_delete'),
]

dashboard/tables/purchase_history/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('purchase_history',views.PurchaseListView.as_view(), name='purchase_history_index'),
    path('purchase_history/create', views.purchase_history_create, name='purchase_history_create'),
    path('purchase_history/update/<int:pk>', views.purchase_history_edit, name='purchase_history_edit'),
    path('purchase_history/delete/<int:pk>', views.purchase_history_delete, name='purchase_history_delete'),
]

dashboard/tables/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shop',views.ShopListView.as_view(), name='shop_index'),
    path('shop/create', views.shop_create, name='shop_create'),
    path('shop/update/<int:pk>', views.shop_edit, name='shop_edit'),
    path('shop/delete/<int:pk>', views.shop_delete, name='shop_delete'),
]

dashboard/urls.py
from django.urls import path, re_path, include
from dashboard import views
 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('welcome', views.welcome, name='welcome'),
    path('profile', views.profile_index, name='profile_index'),
    path('', views.welcome, name='welcome'),
    path('',include('dashboard.tables.shop.urls')),
    path('',include('dashboard.tables.actual_purchase.urls')),
    path('',include('dashboard.tables.product.urls')),
    path('',include('dashboard.tables.purchase_history.urls')),
    
    path('pages', views.pages, name='pages'), 
]

dashboard_authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name='dashboard_auth'

urlpatterns = [
     path('login', login_view, name="login"), 
     path('register', register_user, name="register"),
     path("logout", LogoutView.as_view(), name="logout"),
]

shop_app/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from . import views
from rest_framework_simplejwt import views as jwt_views


app_name = 'shop_app'

#EXCLUDED_URLS_FOR_MAIN_APP = [settings.STATIC_URL.strip('/'),settings.MEDIA_URL.strip('/'),'api']

urlpatterns = [
    path('api/user', views.AuthProfileView.as_view()),
    path('api/products', views.ProductView.as_view()),
    path('api/products/<int:pk>', views.ProductDetailView.as_view()),
    path('api/filters', views.ProductFiltersView.as_view()),
    path('api/purchases', views.PurchaseView.as_view()),
    path('api/purchase/order', views.PurchaseView.as_view()),
    path('api/purchase/order_by_bot', views.PurchaseOrderByBotView.as_view()),
    path('api/download-db', views.download_database),
    path('api/csrf',views.CsrfTokenView.as_view()),
    path('api/token/', 
          jwt_views.TokenObtainPairView.as_view(), 
          name ='token_obtain_pair'),
    path('api/token/refresh/', 
          jwt_views.TokenRefreshView.as_view(), 
          name ='token_refresh'),
    re_path(r'^(?!media|static).*$', views.index, name='main_app'),
    #path('', views.index, name='main_app'),
]

uhf_rfid_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/auth/', include('dashboard_authentication.urls',namespace='dashboard_auth')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('', include('shop_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/tables/actual_purchase/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.html import format_html
from django.urls import reverse
import django_tables2 as tables
import django_filters
from django_filters.views import FilterView 



from shop_app.models import *
from .forms import *
from dashboard.decorators import group_required, OwnerRequiredMixin

@login_required()
@group_required(['shop-owner'])
def actual_purchase_create(request):
    if request.method == 'POST':
        form = PurchaseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
    else:
        form = PurchaseForm(user=request.user)
    return render(request, 'dashboard/tables/form_base.html', {'form': form})

@login_required()
@group_required(['shop-owner'])
def actual_purchase_edit(request, pk):
    actual_purchase = get_object_or_404(Purchase, pk=pk)
    if request.method == 'POST':
        form = PurchaseForm(request.POST, request.FILES, instance=actual_purchase)
        # if form.is_valid():
        #     form.save()
        #     return JsonResponse({'success': True})
    else:
        form = PurchaseForm(instance=actual_purchase)
    return render(request, 'dashboard/tables/form_base.html', {'form': form, 'edit_url': reverse('dashboard:actual_purchase_edit', kwargs={'pk': actual_purchase.pk}) })

@login_required
@group_required(['shop-owner'])
def actual_purchase_delete(request, pk):
    actual_purchase = get_object_or_404(Purchase, pk=pk)
    if request.method == 'POST':
        actual_purchase.delete()
        return redirect('dashboard:actual_purchase_index')
    raise Http404

class PurchaseFilter(django_filters.FilterSet):
    class Meta:
        model = Purchase
        fields = ['id', 'user',]

class PurchaseTable(tables.Table):
    actions = tables.TemplateColumn(
        '<div class="dropdown">'
            '<button class="btn btn-secondary dropdown-toggle" type="button" '
                'data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
                'Actions</button>'
                '<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">'
                '<a class="dropdown-item edit-button" data-url="{% url \'dashboard:actual_purchase_edit\' pk=record.pk %}">Edit</a>'
                '<a class="dropdown-item detail-button">Detail</a>'
                '<a class="">'
                    '<form method="post" action="{% url \'dashboard:actual_purchase_delete\' pk=record.pk %}">'
                        '{% csrf_token %}'
                        '<button class=" delete-button dropdown-item" type="submit">Delete</button>'
                    '</form>'
                '</a>'
            '</div>'
        '</div>',
        verbose_name='Actions'
    )

    class Meta:
        model = Purchase
        fields = ("id","user","total_price",  "created_at" )
        attrs = {
            'class': 'table table-hover',
        }
        row_attrs = {
            "data-id": lambda record: record.pk
        }
    
    def render_user(self, value, record):
        return f"{value.username}({value.pk})"

class PurchaseListView(LoginRequiredMixin,OwnerRequiredMixin,tables.SingleTableMixin,FilterView):
    model = Purchase
    table_class = PurchaseTable
    template_name = 'dashboard/tables/actual_purchase/index.html'
    paginator_class = tables.LazyPaginator
    filterset_class = PurchaseFilter
    #paginate_by = 1
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["form"] = PurchaseForm()
        context['segment'] = 'actual_purchase_index'
        return context
    
    def get_queryset(self, *args, **kwargs):
        shops = Shop.objects.filter(owner = self.request.user)
        shop_ids = [shop.id for shop in shops]
        purchase_items = PurchaseItem.objects.filter(shop_id__in = shop_ids)
        purchase_item_ids = set([purchase_item.purchase_id for purchase_item in purchase_items])
        return Purchase.objects.filter(id__in = purchase_item_ids, status = "PENDING")

dashboard/tables/product/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.html import format_html
from django.urls import reverse
import django_tables2 as tables
import django_filters
from django_filters.views import FilterView 



from shop_app.models import *
from .forms import *
from dashboard.decorators import group_required, OwnerRequiredMixin

@login_required()
@group_required(['shop-owner'])
def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
    else:
        form = ProductForm(user=request.user)
    return render(request, 'dashboard/tables/form_base.html', {'form': form})

@login_required()
@group_required(['shop-owner'])
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        # else:
        #     return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = ProductForm(instance=product, user=request.user)
    return render(request, 'dashboard/tables/form_base.html', {'form': form, 'edit_url': reverse('dashboard:product_edit', kwargs={'pk': product.pk}) })

@login_required
@group_required(['shop-owner'])
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        return redirect('dashboard:product_index')
    raise Http404

class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = Product
        fields = ['id', 'name',"shop", "type",]

class ImageColumn(tables.Column):
    def render(self, value):
        # if not value or not value.url:
        #     return '<img src="/media/product/image/unknown-product.jpg" />'
        return format_html('<img src="{}" width=\'50\' height=\'50\'/>', value.url)
    
class ProductTable(tables.Table):
    image = ImageColumn(orderable=False, default=format_html("<img src='/media/product/image/unknown-product.jpg' width=\'50\' height=\'50\'/>"))
    actions = tables.TemplateColumn(
        '<div class="dropdown">'
            '<button class="btn btn-secondary dropdown-toggle" type="button" '
                'data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
                'Actions</button>'
                '<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">'
                '<a class="dropdown-item edit-button" data-url="{% url \'dashboard:product_edit\' pk=record.pk %}">Edit</a>'
                '<a class="dropdown-item" href="{% url \'dashboard:product_index\' %}?shop={{ record.shop.pk }}">Filter By Shop</a>'
                '<a class="">'
                    '<form method="post" action="{% url \'dashboard:product_delete\' pk=record.pk %}">'
                        '{% csrf_token %}'
                        '<button class=" delete-button dropdown-item" type="submit">Delete</button>'
                    '</form>'
                '</a>'
            '</div>'
        '</div>',
        verbose_name='Actions'
    )

    class Meta:
        model = Product
        #template_name = "django_tables2/bootstrap.html"
        fields = ("id","name","shop", "type", "image", "created_at" )
        attrs = {
            'class': 'table table-hover',
        }
        row_attrs = {
            "data-id": lambda record: record.pk
        }
    
    def render_shop(self, value, record):
        return f"{value.name}({value.pk})"
    def render_type(self, value, record):
        return f"{value.name}({value.pk})"

class ProductListView(LoginRequiredMixin,OwnerRequiredMixin,tables.SingleTableMixin,FilterView):
    model = Product
    table_class = ProductTable
    template_name = 'dashboard/tables/product/index.html'
    paginator_class = tables.LazyPaginator
    filterset_class = ProductFilter
    #paginate_by = 1
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["form"] = ProductForm(user= self.request.user)
        context['segment'] = 'product_index'
        return context
    def get_queryset(self, *args, **kwargs):
        shops = Shop.objects.filter(owner = self.request.user)
        shop_ids = [shop.id for shop in shops]
        return Product.objects.filter(shop_id__in = shop_ids)

dashboard/tables/shop/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, Http404
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from dashboard.decorators import group_required
from shop_app.models import *
from .forms import *

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.html import format_html
from django.urls import reverse
import django_tables2 as tables
import django_filters
from django_filters.views import FilterView 



from shop_app.models import *
from .forms import *
from dashboard.decorators import group_required, OwnerRequiredMixin

@login_required()
@group_required(['shop-owner'])
def shop_create(request):
    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.owner = request.user
            shop.save()
            form.save()
            return JsonResponse({'success': True})
    else:
        form = ShopForm(user=request.user)
    return render(request, 'dashboard/tables/form_base.html', {'form': form})

@login_required()
@group_required(['shop-owner'])
def shop_edit(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
    else:
        form = ShopForm(instance=shop)
    return render(request, 'dashboard/tables/form_base.html', {'form': form, 'edit_url': reverse('dashboard:shop_edit', kwargs={'pk': shop.pk}) })

@login_required
@group_required(['shop-owner'])
def shop_delete(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    if request.method == 'POST':
        shop.delete()
        return redirect('dashboard:shop_index')
    raise Http404

class ShopFilter(django_filters.FilterSet):
    class Meta:
        model = Shop
        fields = ['id', 'name']
    
class ShopTable(tables.Table):
    actions = tables.TemplateColumn(
        '<div class="dropdown">'
            '<button class="btn btn-secondary dropdown-toggle" type="button" '
                'data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
                'Actions</button>'
                '<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">'
                '<a class="dropdown-item edit-button" data-url="{% url \'dashboard:shop_edit\' pk=record.pk %}">Edit</a>'
                '<a class="dropdown-item" href="{% url \'dashboard:product_index\' %}?shop={{ record.pk }}">Products</a>'
                '<a class="">'
                    '<form method="post" action="{% url \'dashboard:shop_delete\' pk=record.pk %}">'
                        '{% csrf_token %}'
                        '<button class=" delete-button dropdown-item" type="submit">Delete</button>'
                    '</form>'
                '</a>'
            '</div>'
        '</div>',
        verbose_name='Actions'
    )

    class Meta:
        model = Shop
        fields = ("id","name","address", "created_at" )
        attrs = {
            'class': 'table table-hover',
        }
        row_attrs = {
            "data-id": lambda record: record.pk
        }

class ShopListView(LoginRequiredMixin,OwnerRequiredMixin,tables.SingleTableMixin,FilterView):
    model = Shop
    table_class = ShopTable
    template_name = 'dashboard/tables/shop/index.html'
    paginator_class = tables.LazyPaginator
    filterset_class = ShopFilter
    #paginate_by = 1
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["form"] = ShopForm()
        context['segment'] = 'shop_index'
        return context
    
    def get_queryset(self, *args, **kwargs):
        return Shop.objects.filter(owner = self.request.user)

dashboard/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
        <a href="/" class="b-brand">
            <div class="b-bg">
                <i class="feather icon-trending-up"></i>
            </div>
            <span class="b-title">Datta Able</span>
        </a>
    </div>
    <a class="mobile-menu" id="mobile-header" href="javascript:">
        <i class="feather icon-more-horizontal"></i>
    </a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
                    class="feather icon-maximize"></i></a></li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Actions</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="javascript:">Action 1</a></li>
                    <li><a class="dropdown-item" href="javascript:">Another action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <div class="main-search">
                    <div class="input-group">
                        <input type="text" id="m-search" class="form-control" placeholder="Search . . .">
                        <a href="javascript:" class="input-group-append search-close">
                            <i class="feather icon-x input-group-text"></i>
                        </a>
                        <span class="input-group-append search-btn btn btn-primary">
                                <i class="feather icon-search input-group-text"></i>
                            </span>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li>
                <label>
                    <i class="icon feather icon-sun" id="theme-indicator"></i>
                    <input type="checkbox" id="theme-switch" class="d-none">
                </label>
            </li>
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"><i
                            class="icon feather icon-bell"></i></a>
                    <div class="dropdown-menu dropdown-menu-right notification">
                        <div class="noti-head">
                            <h6 class="d-inline-block m-b-0">Notifications</h6>
                            <div class="float-right">
                                <a href="javascript:" class="m-r-10">mark as read</a>
                                <a href="javascript:">clear all</a>
                            </div>
                        </div>
                        <ul class="noti-body">
                            <li class="n-title">
                                <p class="m-b-0">NEW</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>John Doe</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>New ticket Added</p>
                                    </div>
                                </div>
                            </li>
                            <li class="n-title">
                                <p class="m-b-0">EARLIER</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-2.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Joseph William</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>Prchace New Theme and make payment</p>
                                    </div>
                                </div>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-3.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>currently login</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <div class="noti-footer">
                            <a href="javascript:">show all</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="dropdown drp-user">
                    <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon feather icon-settings"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">
                            <img src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image">
                            <span>
                                {{ request.user.username }}    
                            </span>
                            <a href="/auth-signin.html" class="dud-logout" title="Logout">
                                <i class="feather icon-log-out"></i>
                            </a>
                        </div>
                        <ul class="pro-body">
                            <li><a href="/profile.html" class="dropdown-item"><i class="feather icon-user"></i>
                                Profile</a></li>
                            <li><a href="{% url 'dashboard_auth:logout' %}" class="dropdown-item">
                                <i class="feather icon-lock"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</header>
<!-- [ Header ] end -->

dashboard/templates/includes/scripts.html
<script src="/static/assets/js/vendor-all.min.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/assets/js/pcoded.min.js"></script>
<script src="/static/assets/js/dark-mode.js"></script>
<script>
    $(document).ready(function(){
        var modal = $('#dashboard-form-modal');
        var saveButton = $('#save-button'),
            saveEditButton = $("#save-edit-button");
        saveButton.click(function() {
          const form = $('#dashboard-form')
          var url = form.attr('action');
          var data = form.serialize();
          var data = new FormData(document.getElementById('dashboard-form'));
          $.ajax({
            type: 'POST',
            url,
            processData: false,
            contentType: false,
            data,
            success: (response) => {
              if (response) {
                modal.modal('hide');
                location.reload();
              }
            },
            error: (response) =>{
              console.log(response)
              form.html(response);
            }
          } );
        });
        $('.edit-button').click(function(){
          openEditModalProf(this)
        })
        openEditModalProf = (el) => {
            
            const loadUrl = $(el).data('load-url')
            const url = $(el).data('url')
            //var url = form.attr('item-id');
            $.get(loadUrl || url, {}, (response) => {
              if (response) {
                modal.find('.modal-body').html(response)
                modal.modal('show');
              } else {
                
                form.html(response);
              }
            } );
          }
        saveEditButton.click(function() {
          const form = $('#dashboard-form')
          var url = form.attr('action');
          var data = new FormData(document.getElementById('dashboard-form'));
          $.ajax({
            type: 'POST',
            url,
            processData: false,
            contentType: false,
            data,
            success: (response) => {
              if (response) {
                modal.modal('hide');
                location.reload();
              }
            },
            error: (response) =>{
              form.html(response);
            }
          })
        });
      })
      
    
</script>
<style>
    .error {
        border: 1px solid red !important;
    }

    .error-text {
        color: red !important;
        font-size: 12px !important;
    }
  </style>

dashboard/templates/includes/sidebar.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="{% url 'dashboard:index' %}" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-trending-up"></i>
                </div>
                <span class="b-title">Dashboard</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="{% url 'dashboard:index' %}"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Navigation</label>
                </li>
                <li data-username="Profile Dashboard Page" 
                    class="nav-item {% if 'profile_index' in segment %} active {% endif %}">
                    <a href="{% url 'dashboard:profile_index' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                            <span class="pcoded-mtext">Profile</span></a>
                </li>

                <li class="nav-item pcoded-menu-caption">
                    <label>Tables</label>
                </li>
                    <li data-username="Shop Dashboard Page" 
                        class="nav-item {% if 'shop_index' in segment %} active {% endif %}">
                        <a href="{% url 'dashboard:shop_index' %}" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                                <span class="pcoded-mtext">Shops</span></a>
                    </li>
                    <li data-username="Shop Dashboard Page" 
                        class="nav-item {% if 'actual_purchase_index' in segment %} active {% endif %}">
                        <a href="{% url 'dashboard:actual_purchase_index' %}" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                                <span class="pcoded-mtext">Actual Purchases</span></a>
                    </li>
                    <li data-username="Shop Dashboard Page" 
                        class="nav-item {% if 'purchase_history_index' in segment %} active {% endif %}">
                        <a href="{% url 'dashboard:purchase_history_index' %}" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                                <span class="pcoded-mtext">Purchase History</span></a>
                    </li>
                    <li data-username="Shop Dashboard Page" 
                        class="nav-item {% if 'product_index' in segment %} active {% endif %}">
                        <a href="{% url 'dashboard:product_index' %}" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                                <span class="pcoded-mtext">Products</span></a>
                    </li>

                <li class="nav-item pcoded-menu-caption">
                    <label>Action</label>
                </li>


                <li data-username="Disabled Menu" class="nav-item">
                    <a href="{% url 'dashboard_auth:logout' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->